# Generated by Django 3.2.7 on 2022-04-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_assignment_feedfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='assignment_files/')),
            ],
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='FeedFiles',
        ),
        migrations.AddField(
            model_name='feedfile',
            name='assignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.assignment'),
        ),
    ]
