# Generated by Django 3.2.7 on 2022-04-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20220413_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedfile',
            name='assignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment'),
        ),
    ]
