# Generated by Django 3.2.7 on 2022-04-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_feedfile_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created_at',
        ),
    ]
