# Generated by Django 3.2.7 on 2022-04-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20220424_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedfile',
            name='title',
        ),
    ]
